services:
  - type: web
    name: local-share
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: main
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" 